version: "3.3"

services:
  mongy_mongo:
    image: mongo:4.4.1-bionic
    container_name: mongy_mongo
    env_file: .env
    ports:
      - 27017:27017

  mongy_app:
    build: .
    image: mongy_app:latest
    container_name: mongy_app
    depends_on:
      - mongy_mongo
    env_file: .env
