name: Build and test.

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited]
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: List all files.
        run: |
          ls -l
      - name: Docker build.
        run: docker-compose build mongy_app
      - name: Create env file.
        run: |
          touch .env
          echo MONGO_INITDB_DATABASE=Mongy >> .env
          echo MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_USERNAME }} >> .env
          echo MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_PASSWORD }} >> .env
          echo MONGO_HOST=mongy_mongo >> .env
          echo MONGO_DATA_DIR=/data/db >> .env
          echo MONGO_LOG_DIR=/dev/null >> .env
      - name: Run tests.
        run: docker-compose up mongy_app
